# -*- coding: utf-8; -*-
#
# This file is part of Superdesk.
#
# Copyright 2013, 2014, 2015 Sourcefabric z.u. and contributors.
#
# For the full copyright and license information, please see the
# AUTHORS and LICENSE files distributed with this source code, or
# at https://www.sourcefabric.org/superdesk/license

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(message)s level=%(levelname)s function=%(funcName)s process=%(processName)s'
handlers:
  console:
    class: logging.StreamHandler
    stream  : ext://sys.stdout
    formatter: simple
  logstash:
    class: logging.handlers.SysLogHandler
    address: !!python/tuple [sd-uat-sy4-log-1.aap.com.au, 5555]
    formatter: simple
loggers:
  # superdesk.ws - used for debug message can be removed later on.
  newsroom:
    handlers: [console, logstash]
    level: INFO
  worker:
    handlers: [console, logstash]
    level: INFO
  root:
    handlers: [console, logstash]

